import styles from './profile.module.css';

export default function Profile() {
    return (
        <div className={`${styles.wrapper}`}>
            <h1>My Profile</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic, id eum explicabo tempore itaque officiis sint. Veniam tempore officia impedit eligendi ad quasi fugiat. Error ut provident temporibus sapiente laudantium molestias adipisci necessitatibus culpa quae tempore unde esse eum maxime doloribus, voluptates voluptatibus qui, nulla quod beatae. Facilis sit dolor excepturi, culpa enim perferendis unde nulla modi id nostrum perspiciatis aliquam numquam error vitae hic consectetur. Harum reiciendis libero perspiciatis. Quod placeat aliquam commodi facilis, voluptas eveniet saepe libero vitae asperiores. Animi, maiores explicabo molestias corrupti impedit eum error, eveniet sapiente totam magni atque nisi ipsa voluptate minus nam quidem quis eligendi aliquid soluta asperiores optio. Minima autem hic mollitia dolore distinctio! Ipsam, repudiandae aut. Dolores ad, beatae, non, vel necessitatibus exercitationem cupiditate iste doloremque dolor a corporis qui! Ipsa ex quae sequi dolores exercitationem? Aspernatur, eaque sapiente dolor optio nam voluptate consequatur provident similique ab numquam alias. Soluta laudantium fugit culpa maiores iusto debitis quam, quidem nesciunt temporibus ab. Sit iusto reiciendis blanditiis atque ab? Aut, fugit ipsum ut quod error dolores natus dignissimos beatae excepturi libero quo consectetur rerum at officiis impedit velit commodi molestias laudantium soluta doloribus. Rerum porro illum aliquid suscipit voluptate, beatae tenetur quae ipsum?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic, id eum explicabo tempore itaque officiis sint. Veniam tempore officia impedit eligendi ad quasi fugiat. Error ut provident temporibus sapiente laudantium molestias adipisci necessitatibus culpa quae tempore unde esse eum maxime doloribus, voluptates voluptatibus qui, nulla quod beatae. Facilis sit dolor excepturi, culpa enim perferendis unde nulla modi id nostrum perspiciatis aliquam numquam error vitae hic consectetur.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic, id eum explicabo tempore itaque officiis sint. Veniam tempore officia impedit eligendi ad quasi fugiat. Error ut provident temporibus sapiente laudantium molestias adipisci necessitatibus culpa quae tempore unde esse eum maxime doloribus, voluptates voluptatibus qui, nulla quod beatae. Facilis sit dolor excepturi, culpa enim perferendis unde nulla modi id nostrum perspiciatis aliquam numquam error vitae hic consectetur. Harum reiciendis libero perspiciatis. Quod placeat aliquam commodi facilis, voluptas eveniet saepe libero vitae asperiores. Animi, maiores explicabo molestias corrupti impedit eum error, eveniet sapiente totam magni atque nisi ipsa voluptate minus nam quidem quis eligendi aliquid soluta asperiores optio. Minima autem hic mollitia dolore distinctio! Ipsam, repudiandae aut.</p>
        </div>
    );
}